language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/pawgrmr/ci/staging/build-package.sh | sh'

git:
  depth: 10

branches:
  only:
    - staging
